applications/department/urls.py
from django.contrib import admin
from django.urls import path
from .views import DepartmentView, ListAllDepartment

'''def department(self):
    print('********************* SALUDOS DESDE LA APP DEPARTMENT ************************')'''

app_name = 'department_app'

urlpatterns = [
    path('department-create/', DepartmentView.as_view(), name='department-create'),
    path('list-all-department/', ListAllDepartment.as_view(), name='list-all-department'),
]

applications/employee/urls.py
from django.contrib import admin
from django.urls import path
from .views import (ListAllEmployee, ListEmployeeByArea,
                    ListEmployeeByKword, ListEmployeSkill,
                    EmployeDetailView, EmployeeCreateView,
                    SuccessCreateView, EmployeeUpdateView,
                    EmployeeDeleteView, EmployeeSuccessDeleteView,
                    IndexView,
                    )

'''def employee(self):
    print('********************* SALUDOS DESDE LA APP EMPLEADO ************************')'''

app_name = 'employee_app'

urlpatterns = [
    #path('employee/', employee),
    path('', IndexView.as_view(), name='index'),
    path('list-all-employee/', ListAllEmployee.as_view(), name='list-all-employee'),
    path('list-employee-by-area/<short_name>', ListEmployeeByArea.as_view(), name='list-employee-by-area'),
    path('list-employee-by-kword/', ListEmployeeByKword.as_view(), name='list-employee-by-kword'),
    path('employee-skill/', ListEmployeSkill.as_view(), name='employee-skill'),
    path('employee-detail/<pk>', EmployeDetailView.as_view(), name='employee-detail'),
    path('employee-create/', EmployeeCreateView.as_view(), name='employee-create'),
    path('success-create/', SuccessCreateView.as_view(), name='success-create'),
    path('employee-update/<pk>', EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee-delete/<pk>', EmployeeDeleteView.as_view(), name='employee-delete'),
    path('success-delete/', EmployeeSuccessDeleteView.as_view(), name='employee-success-delete'),
]

registroempleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de la apps creadas
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.department.urls')),
    re_path('', include('applications.employee.urls')),
]

templates/includes/header.html
<div class="navbar-fixed">
<nav>
    <div class="nav-wrapper">
        <a href="{% url 'employee_app:index' %}" class="brand-logo">REGISTRO EMPLEADOS</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul class="right hide-on-med-and-down">
            <li><a href="{% url 'employee_app:list-all-employee' %}">Listar</a></li>
            <li><a href="{% url 'department_app:list-all-department' %}">Departamentos</a></li>
            <li><a href="#">Administrar</a></li>
            <li><a href="{% url 'employee_app:employee-create' %}" class="waves-effect waves-light btn">Registrar nuevo</a></li>
        </ul>
    </div>
</nav>
</div>

<ul class="sidenav" id="mobile-demo">
    <li><a href="{% url 'employee_app:list-all-employee' %}">Listar</a></li>
    <li><a href="#">Departamentos</a></li>
    <li><a href="#">Administrar</a></li>
    <li><a href="{% url 'employee_app:employee-create' %}">Registrar nuevo</a></li>
</ul>