applications/department/urls.py
from django.contrib import admin
from django.urls import path
from .views import DepartmentView, ListAllDepartment

'''def department(self):
    print('********************* SALUDOS DESDE LA APP DEPARTMENT ************************')'''

app_name = 'department_app'

urlpatterns = [
    path('department-create/', DepartmentView.as_view(), name='department-create'),
    path('list-all-department/', ListAllDepartment.as_view(), name='list-all-department'),
]

applications/employee/urls.py
from django.contrib import admin
from django.urls import path
from .views import (ListAllEmployee, ListEmployeeByArea,
                    ListEmployeeByKword, ListEmployeSkill,
                    EmployeDetailView, EmployeeCreateView,
                    SuccessCreateView, EmployeeUpdateView,
                    EmployeeDeleteView, EmployeeSuccessDeleteView,
                    IndexView,
                    )

'''def employee(self):
    print('********************* SALUDOS DESDE LA APP EMPLEADO ************************')'''

app_name = 'employee_app'

urlpatterns = [
    #path('employee/', employee),
    path('', IndexView.as_view(), name='index'),
    path('list-all-employee/', ListAllEmployee.as_view(), name='list-all-employee'),
    path('list-employee-by-area/<short_name>', ListEmployeeByArea.as_view(), name='list-employee-by-area'),
    path('list-employee-by-kword/', ListEmployeeByKword.as_view(), name='list-employee-by-kword'),
    path('employee-skill/', ListEmployeSkill.as_view(), name='employee-skill'),
    path('employee-detail/<pk>', EmployeDetailView.as_view(), name='employee-detail'),
    path('employee-create/', EmployeeCreateView.as_view(), name='employee-create'),
    path('success-create/', SuccessCreateView.as_view(), name='success-create'),
    path('employee-update/<pk>', EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee-delete/<pk>', EmployeeDeleteView.as_view(), name='employee-delete'),
    path('success-delete/', EmployeeSuccessDeleteView.as_view(), name='employee-success-delete'),
]

registroempleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de la apps creadas
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.department.urls')),
    re_path('', include('applications.employee.urls')),
]

applications/department/models.py
from django.db import models

# Create your models here.
class Department(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre Corto', max_length=20, unique=True)

    class Meta:
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    def __str__(self):
        return self.short_name

applications/department/forms.py
from django import forms

class DepartmentForm(forms.Form):
    '''Datos del empleado'''
    name = forms.CharField(label='Nombres', widget=forms.TextInput(
                            attrs={'placeholder': 'Nombres del empleado'}),
                            error_messages={'required': 'Digite los nombres del empleado'}
                           )
    last_name = forms.CharField(label='Apellidos', widget=forms.TextInput(
                                attrs={'placeholder': 'Apellidos del empleado'}),
                                error_messages={'required': 'Digite los apellidos del empleado'}
                                )
    '''Datos del departamendo'''
    department = forms.CharField(label='Nombre del departamento', widget=forms.TextInput(
                                attrs={'placeholder': 'Nombre del departamento'}),
                                error_messages={'required': 'Digite el nombre del departamento'}
                                 )
    short_name = forms.CharField(label='Nombre corto', widget=forms.TextInput(
                                attrs={'placeholder': 'Nombre corto departamento'}),
                                error_messages={'required': 'Digite un nombre corto para el departamento'}
                                 )

applications/department/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from applications.employee.models import Employee
from .models import Department
from .forms import DepartmentForm
from django.views.generic.edit import FormView

class DepartmentView(FormView):
    template_name = 'department/department_create.html'
    form_class = DepartmentForm
    success_url = reverse_lazy('employee_app:success-create')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        last_name = form.cleaned_data['last_name']
        department = form.cleaned_data['department']
        short_name = form.cleaned_data['short_name']
        depto = Department(name = department, short_name = short_name)
        depto.save()
        Employee.objects.create(
            first_name = name,
            last_name = last_name,
            job = '1',
            department = depto
        )
        return super().form_valid(form)

class ListAllDepartment(ListView):
    template_name = 'department/list_all_department.html'
    model = Department
    context_object_name = 'department_list'

templates/department/department_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Crear Departamento</title>
</head>
<body>
    <h1>Crear Departamento</h1>
    <form method="post">{% csrf_token %}
        <h1>Datos del empleado</h1>
        <p>{{ form.name }}</p>
        <p>{{ form.last_name }}</p>
        <h1>Datos del departamento</h1>
        <p>{{ form.department }}</p>
        <p>{{ form.short_name }}</p>
        <input type="submit" value="Guardar">
    </form>
</body>
</html>

templates/department/list_all_department.html
{% extends 'base.html' %}
{% block title %}Lista de departamentos{% endblock title %}

{% block content %}
{% load static %}

    <h1 class="title">Lista de departamentos de la empresa</h1>

    <table class="striped centered">
        <thead>
            <tr>
                <th>Departamento</th>
                <th>Nombre corto</th>
                <th>Empleados del departamento</th>
            </tr>
        </thead>

        <tbody>
            {% for depto in department_list %}
                <tr>
                    <td>{{depto.name}}</td>
                    <td>{{depto.short_name}}</td>
                    <td>
                        <a href="{% url 'employee_app:list-employee-by-area' depto.short_name %}" class="waves-effect waves-light btn">
                            <i class="material-icons left">visibility</i>
                            Ver empleados
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}