applications/employee/urls.py
from django.contrib import admin
from django.urls import path
from .views import (ListAllEmployee, ListEmployeeByArea,
                    ListEmployeeByKword, ListEmployeSkill,
                    EmployeDetailView, EmployeeCreateView,
                    SuccessCreateView, EmployeeUpdateView,
                    EmployeeDeleteView, EmployeeSuccessDeleteView,
                    IndexView,
                    )

'''def employee(self):
    print('********************* SALUDOS DESDE LA APP EMPLEADO ************************')'''

app_name = 'employee_app'

urlpatterns = [
    #path('employee/', employee),
    path('', IndexView.as_view(), name='index'),
    path('list-all-employee/', ListAllEmployee.as_view(), name='list-all-employee'),
    path('list-employee-by-area/<short_name>', ListEmployeeByArea.as_view(), name='list-employee-by-area'),
    path('list-employee-by-kword/', ListEmployeeByKword.as_view(), name='list-employee-by-kword'),
    path('employee-skill/', ListEmployeSkill.as_view(), name='employee-skill'),
    path('employee-detail/<pk>', EmployeDetailView.as_view(), name='employee-detail'),
    path('employee-create/', EmployeeCreateView.as_view(), name='employee-create'),
    path('success-create/', SuccessCreateView.as_view(), name='success-create'),
    path('employee-update/<pk>', EmployeeUpdateView.as_view(), name='employee-update'),
    path('employee-delete/<pk>', EmployeeDeleteView.as_view(), name='employee-delete'),
    path('success-delete/', EmployeeSuccessDeleteView.as_view(), name='employee-success-delete'),
]

applications/home/urls.py
from django.contrib import admin
from django.urls import path
from .views import HomeView, HomeListView

urlpatterns = [
    path('list/', HomeListView.as_view()),
]

registroempleados/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluimos las urls de la apps creadas
    re_path('', include('applications.home.urls')),
    re_path('', include('applications.department.urls')),
    re_path('', include('applications.employee.urls')),
]

applications/employee/models.py
from django.db import models
from applications.department.models import Department
from ckeditor.fields import RichTextField

# Create your models here.
class Skill(models.Model):
    skill = models.CharField('Habilidad', max_length=50, unique=True)

    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return self.skill

class Employee(models.Model):
    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('3', 'Otro')
    )
    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    job = models.CharField('Trabajo',max_length=1, choices=JOB_CHOICES)
    department = models.ForeignKey(Department, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    skills = models.ManyToManyField(Skill)
    curriculum = RichTextField(default='texto')

    class Meta:
        verbose_name = 'Empleado'
        verbose_name_plural = 'Empleados'
        ordering = ['first_name', 'last_name']

    def __str__(self):
        return self.first_name + ' ' +self.last_name

applications/employee/views.py
from django.shortcuts import render
from django.db.models import Q
from django.urls import reverse_lazy
from django.views.generic import (
        ListView, DetailView,
        CreateView, TemplateView,
        UpdateView, DeleteView
    )
from .models import Employee
# Create your views here.

class IndexView(TemplateView):
    template_name = 'index.html'

class ListAllEmployee(ListView):
    template_name = 'employee/list_all_employee.html'
    paginate_by = 4
    model = Employee
    '''context_object_name = 'employee_list'''

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        kword = self.request.GET.get('kword',)
        if kword:
            context['employee_list'] = Employee.objects.filter(
                Q(first_name=kword.capitalize()) | Q(last_name=kword.capitalize()))
        else:
            context['employee_list'] = Employee.objects.all()
        return context

class ListEmployeeByArea(ListView):
    '''Lista los empleados que pertenecen a un área específica'''
    #context_object_name = 'list_by_area'
    #queryset = Employee.objects.filter(department__short_name='Contabilidad')
    template_name = 'employee/list_employee_by_area.html'
    model = Employee

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        department = self.kwargs['short_name']
        # Add in the publisher
        context['list_by_area'] = Employee.objects.filter(department__short_name=department)
        return context

class ListEmployeeByKword(ListView):
    template_name = 'employee/list_employee_by_kword.html'
    model = Employee

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        kword = self.request.GET.get('kword',)
        if kword:
            context['list_by_kword'] = Employee.objects.filter(
                Q(first_name=kword.capitalize()) | Q(last_name=kword.capitalize()))
        else:
            context['list_by_kword'] = Employee.objects.filter(
                Q(first_name=kword) | Q(last_name=kword))
        return context

class ListEmployeSkill(ListView):
    template_name = 'employee/employee_skill.html'
    model = Employee

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        employee = Employee.objects.get(id=4)
        context['employee_skills'] = employee.skills.all()
        return context

class EmployeDetailView(DetailView):
    template_name = 'employee/employee_detail.html'
    context_object_name = 'employee'
    model = Employee

class SuccessCreateView(TemplateView):
    template_name = 'employee/success_create.html'

class EmployeeCreateView(CreateView):
    template_name = 'employee/employee_create.html'
    model = Employee
    fields = ('__all__')
    success_url = reverse_lazy('employee_app:success-create')

class EmployeeUpdateView(UpdateView):
    model = Employee
    template_name = 'employee/employee_update.html'
    fields = ('__all__')
    success_url = reverse_lazy('employee_app:success-create')

class EmployeeSuccessDeleteView(TemplateView):
    template_name = 'employee/success_delete.html'

class EmployeeDeleteView(DeleteView):
    model = Employee
    template_name = 'employee/employee_delete.html'
    success_url = reverse_lazy('employee_app:employee-success-delete')

templates/employee/employee_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Crear empleado</title>
</head>
<body>
    <h1>Crear empleado</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Guardar">
    </form>
</body>
</html>

templates/employee/employee_delete.html
<form method="post">{% csrf_token %}
    <h2 style="color:red;">Confirma que desea eliminar el registro "{{ object }}"?</h2>
    <input type="submit" value="Confirmar">
</form>

templates/employee/employee_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Información detallada de un empleado</title>
</head>
<body>
    <h1>Información detallada de un empleado</h1>
    <p><span style="color:black;font-weight:bold;font-size:18px;">Nombre:</span> {{employee.first_name}}</p>
    <p><span style="color:black;font-weight:bold;font-size:18px;">Apellido:</span> {{employee.last_name}}</p>
    <p><span style="color:black;font-weight:bold;font-size:18px;">Trabajo:</span> {{employee.get_job_display}}</p>
    <p><span style="color:black;font-weight:bold;font-size:18px;">Área de la empresa:</span> {{employee.department}}</p>
    <h4>Habilidades: </h4>
        <ul>
            {% for skill in employee.skills.all %}
                <li>{{skill}}</li>
            {% endfor %}
        </ul>
    <h4>Curriculum: </h4>{{employee.curriculum|safe}}
</body>
</html>

templates/employee/employee_skill.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista las habilidades de un empleado</title>
</head>
<body>
    <h1>Lista las habilidades de un empleado</h1>
    {% if employee_skills %}
        Total de habilidades: {{ employee_skills|length }}
        <ul>
            {% for skill in employee_skills %}
                <li><h3>{{skill}}</h3></li>
            {% endfor %}
        </ul>
    {% else %}
        El empleado no tiene habilidades registradas.
    {% endif %}
</body>
</html>

templates/employee/employee_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Actualizar empleado</title>
</head>
<body>
    <h1>Actualizar los datos de un empleado</h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Actualizar datos">
    </form>
</body>
</html>

templates/employee/list_all_employee.html
{% extends 'base.html' %}
{% block title %}Lista de empleados{% endblock title %}

{% block content %}
{% load static %}

    <h1 class="title">Lista de empleados de la empresa</h1>
    <nav class="container">
        <div class="nav-wrapper">
            <form class="row" method="get"> {% csrf_token %}
                <div class="input-field col s12 m9 l10">
                    <input id="kword" name="kword" type="search" required>
                    <label class="label-icon" for="search"><i class="material-icons">search</i></label>
                </div>
                <div class="input-field col s12 m3 l2">
                    <button type="submit" class="waves-effect waves-light btn-large">Buscar</button>
                </div>
            </form>
        </div>
    </nav>

    {% if employee_list %}
        <h5 class="title">Total de empleados: {{ employee_list|length }}</h5>
    {% else %}
    <h4 class="title">No hay empleados.</h4>
    {% endif %}

<table class="striped centered">
    <thead>
        <tr>
            <th>Nombres</th>
            <th>Apellidos</th>
            <th>Trabajo</th>
            <th>Departamento</th>
            <th>Acción</th>
        </tr>
    </thead>

    <tbody>
        {% for employee in employee_list %}
            <tr>
                <td>{{employee.first_name}}</td>
                <td>{{employee.last_name}}</td>
                <td>{{employee.job}}</td>
                <td>{{employee.department}}</td>
                <td>
                    <a href="{% url 'employee_app:employee-detail' employee.id %}"><i style="color:#4caf50;" class="material-icons center">visibility</i></a>
                    <a href="{% url 'employee_app:employee-update' employee.id %}"><i class="material-icons center">edit</i></a>
                    <a href="{% url 'employee_app:employee-delete' employee.id %}"><i style="color:#ef5350;" class="material-icons center">delete</i></a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

<div class="pagination row">
    <span class="step-links col l12 offset-l4">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; Primero</a>
            <a href="?page={{ page_obj.previous_page_number }}">Anterior</a>
        {% endif %}

        <span class="current">
            Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">Próximo</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">Último &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock content %}

templates/employee/list_employee_by_area.html
{% extends 'base.html' %}
{% block title %}Empleados por departamento{% endblock title %}

{% block content %}
{% load static %}
    <h1 class="title">Lista de empleados por departamento</h1>
    {% if list_by_area %}
        <h4 class="title">Total de empleados: {{ list_by_area|length }}</h4>
    {% else %}
    <h4 class="title">No hay empleados.</h4>
    {% endif %}
    <table class="striped centered">
        <thead>
            <tr>
                <th>Nombres</th>
                <th>Apellidos</th>
                <th>Trabajo</th>
                <th>Departamento</th>
                <th>Acción</th>
            </tr>
        </thead>

        <tbody>
            {% for employee in list_by_area %}
                <tr>
                    <td>{{employee.first_name}}</td>
                    <td>{{employee.last_name}}</td>
                    <td>{{employee.job}}</td>
                    <td>{{employee.department}}</td>
                    <td>
                        <a href="{% url 'employee_app:employee-detail' employee.id %}"><i style="color:#4caf50;" class="material-icons center">visibility</i></a>
                        <a href="{% url 'employee_app:employee-update' employee.id %}"><i class="material-icons center">edit</i></a>
                        <a href="{% url 'employee_app:employee-delete' employee.id %}"><i style="color:#ef5350;" class="material-icons center">delete</i></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <!--div class="container">
        {% if list_by_area %}
        <h4 class="title">Total de empleados: {{ list_by_area|length }}</h4>
            <ul>
                {% for employee in list_by_area %}
                    <li><h3>{{employee.first_name}} {{employee.last_name}}</h3></li>
                {% endfor %}
            </ul>
        {% else %}
            No hay empleados.
        {% endif %}
    </div-->
{% endblock content %}

templates/employee/list_employee_by_kword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Lista de empleados por palabra clave</title>
</head>
<body>
    <h1>Lista de empleados por palabra clave</h1>
    <form method="get">{%csrf_token%}
        <input type="text" id="kward" name="kword" placeholder="Ingrese el nombre">
        <button type="submit">Buscar</button>
    </form>
    <br>
    {% if list_by_kword %}
        Total de empleados: {{ list_by_kword|length }}
        <ul>
            {% for employee in list_by_kword %}
                <li><h3>{{employee.first_name}} {{employee.last_name}}</h3></li>
            {% endfor %}
        </ul>
    {% else %}
        No hay empleados.
    {% endif %}
</body>
</html>

templates/employee/success_create.html
<h1 style="color:green;">Empleado agregado con exito!!!</h1>

templates/employee/success_delete.html
<h1 style="color:green;">Empleado eliminado con exito!!!</h1>